// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Acompanhamentos;
import com.roo.viralatas.domain.Adotantes;
import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.PossiveisLocais;
import com.roo.viralatas.domain.Prontuarios;
import com.roo.viralatas.domain.Situacoes;
import com.roo.viralatas.domain.SolicitacaoAdocoes;
import com.roo.viralatas.domain.Status;
import com.roo.viralatas.domain.TipoMoradias;
import com.roo.viralatas.domain.Usuarios;
import com.roo.viralatas.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<Acompanhamentos, String> ApplicationConversionServiceFactoryBean.getAcompanhamentosToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Acompanhamentos, java.lang.String>() {
            public String convert(Acompanhamentos acompanhamentos) {
                return new StringBuilder().append(acompanhamentos.getIdSolicitacaoAdocaoSolicitacaoAdocao()).append(' ').append(acompanhamentos.getStatusAcompanhamento()).append(' ').append(acompanhamentos.getComentario()).toString();
            }
        };
    }
    
    public Converter<Integer, Acompanhamentos> ApplicationConversionServiceFactoryBean.getIdToAcompanhamentosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Acompanhamentos>() {
            public com.roo.viralatas.domain.Acompanhamentos convert(java.lang.Integer id) {
                return Acompanhamentos.findAcompanhamentos(id);
            }
        };
    }
    
    public Converter<String, Acompanhamentos> ApplicationConversionServiceFactoryBean.getStringToAcompanhamentosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Acompanhamentos>() {
            public com.roo.viralatas.domain.Acompanhamentos convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Acompanhamentos.class);
            }
        };
    }
    
    public Converter<Adotantes, String> ApplicationConversionServiceFactoryBean.getAdotantesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Adotantes, java.lang.String>() {
            public String convert(Adotantes adotantes) {
                return new StringBuilder().append(adotantes.getRendaFamiliar()).append(' ').append(adotantes.getCriancasEmCasa()).append(' ').append(adotantes.getQuantidadeanimais()).append(' ').append(adotantes.getReputacao()).toString();
            }
        };
    }
    
    public Converter<Integer, Adotantes> ApplicationConversionServiceFactoryBean.getIdToAdotantesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Adotantes>() {
            public com.roo.viralatas.domain.Adotantes convert(java.lang.Integer id) {
                return Adotantes.findAdotantes(id);
            }
        };
    }
    
    public Converter<String, Adotantes> ApplicationConversionServiceFactoryBean.getStringToAdotantesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Adotantes>() {
            public com.roo.viralatas.domain.Adotantes convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Adotantes.class);
            }
        };
    }
    
    public Converter<Animais, String> ApplicationConversionServiceFactoryBean.getAnimaisToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Animais, java.lang.String>() {
            public String convert(Animais animais) {
                return new StringBuilder().append(animais.getNome()).append(' ').append(animais.getDataNascimento()).append(' ').append(animais.getRaca()).append(' ').append(animais.getCor()).toString();
            }
        };
    }
    
    public Converter<Integer, Animais> ApplicationConversionServiceFactoryBean.getIdToAnimaisConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Animais>() {
            public com.roo.viralatas.domain.Animais convert(java.lang.Integer id) {
                return Animais.findAnimais(id);
            }
        };
    }
    
    public Converter<String, Animais> ApplicationConversionServiceFactoryBean.getStringToAnimaisConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Animais>() {
            public com.roo.viralatas.domain.Animais convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Animais.class);
            }
        };
    }
    
    public Converter<Cidades, String> ApplicationConversionServiceFactoryBean.getCidadesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Cidades, java.lang.String>() {
            public String convert(Cidades cidades) {
                return new StringBuilder().append(cidades.getNome()).append(' ').append(cidades.getEstado()).toString();
            }
        };
    }
    
    public Converter<Integer, Cidades> ApplicationConversionServiceFactoryBean.getIdToCidadesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Cidades>() {
            public com.roo.viralatas.domain.Cidades convert(java.lang.Integer id) {
                return Cidades.findCidades(id);
            }
        };
    }
    
    public Converter<String, Cidades> ApplicationConversionServiceFactoryBean.getStringToCidadesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Cidades>() {
            public com.roo.viralatas.domain.Cidades convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Cidades.class);
            }
        };
    }
    
    public Converter<Enderecos, String> ApplicationConversionServiceFactoryBean.getEnderecosToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Enderecos, java.lang.String>() {
            public String convert(Enderecos enderecos) {
                return new StringBuilder().append(enderecos.getRua()).append(' ').append(enderecos.getNumero()).append(' ').append(enderecos.getComplemento()).append(' ').append(enderecos.getCep()).toString();
            }
        };
    }
    
    public Converter<Integer, Enderecos> ApplicationConversionServiceFactoryBean.getIdToEnderecosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Enderecos>() {
            public com.roo.viralatas.domain.Enderecos convert(java.lang.Integer id) {
                return Enderecos.findEnderecos(id);
            }
        };
    }
    
    public Converter<String, Enderecos> ApplicationConversionServiceFactoryBean.getStringToEnderecosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Enderecos>() {
            public com.roo.viralatas.domain.Enderecos convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Enderecos.class);
            }
        };
    }
    
    public Converter<Feiras, String> ApplicationConversionServiceFactoryBean.getFeirasToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Feiras, java.lang.String>() {
            public String convert(Feiras feiras) {
                return new StringBuilder().append(feiras.getNomeFeira()).append(' ').append(feiras.getDataInicio()).append(' ').append(feiras.getDataEncerramento()).append(' ').append(feiras.getNumeroanimais()).toString();
            }
        };
    }
    
    public Converter<Integer, Feiras> ApplicationConversionServiceFactoryBean.getIdToFeirasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Feiras>() {
            public com.roo.viralatas.domain.Feiras convert(java.lang.Integer id) {
                return Feiras.findFeiras(id);
            }
        };
    }
    
    public Converter<String, Feiras> ApplicationConversionServiceFactoryBean.getStringToFeirasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Feiras>() {
            public com.roo.viralatas.domain.Feiras convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Feiras.class);
            }
        };
    }
    
    public Converter<HistoricoFeiraAnimais, String> ApplicationConversionServiceFactoryBean.getHistoricoFeiraAnimaisToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.HistoricoFeiraAnimais, java.lang.String>() {
            public String convert(HistoricoFeiraAnimais historicoFeiraAnimais) {
                return new StringBuilder().append(historicoFeiraAnimais.getDataRegistro()).toString();
            }
        };
    }
    
    public Converter<Integer, HistoricoFeiraAnimais> ApplicationConversionServiceFactoryBean.getIdToHistoricoFeiraAnimaisConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.HistoricoFeiraAnimais>() {
            public com.roo.viralatas.domain.HistoricoFeiraAnimais convert(java.lang.Integer id) {
                return HistoricoFeiraAnimais.findHistoricoFeiraAnimais(id);
            }
        };
    }
    
    public Converter<String, HistoricoFeiraAnimais> ApplicationConversionServiceFactoryBean.getStringToHistoricoFeiraAnimaisConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.HistoricoFeiraAnimais>() {
            public com.roo.viralatas.domain.HistoricoFeiraAnimais convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), HistoricoFeiraAnimais.class);
            }
        };
    }
    
    public Converter<Moradias, String> ApplicationConversionServiceFactoryBean.getMoradiasToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Moradias, java.lang.String>() {
            public String convert(Moradias moradias) {
                return "(no displayable fields)";
            }
        };
    }
    
    public Converter<Integer, Moradias> ApplicationConversionServiceFactoryBean.getIdToMoradiasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Moradias>() {
            public com.roo.viralatas.domain.Moradias convert(java.lang.Integer id) {
                return Moradias.findMoradias(id);
            }
        };
    }
    
    public Converter<String, Moradias> ApplicationConversionServiceFactoryBean.getStringToMoradiasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Moradias>() {
            public com.roo.viralatas.domain.Moradias convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Moradias.class);
            }
        };
    }
    
    public Converter<PossiveisLocais, String> ApplicationConversionServiceFactoryBean.getPossiveisLocaisToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.PossiveisLocais, java.lang.String>() {
            public String convert(PossiveisLocais possiveisLocais) {
                return new StringBuilder().append(possiveisLocais.getNome()).append(' ').append(possiveisLocais.getLongitude()).append(' ').append(possiveisLocais.getLatitude()).toString();
            }
        };
    }
    
    public Converter<Integer, PossiveisLocais> ApplicationConversionServiceFactoryBean.getIdToPossiveisLocaisConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.PossiveisLocais>() {
            public com.roo.viralatas.domain.PossiveisLocais convert(java.lang.Integer id) {
                return PossiveisLocais.findPossiveisLocais(id);
            }
        };
    }
    
    public Converter<String, PossiveisLocais> ApplicationConversionServiceFactoryBean.getStringToPossiveisLocaisConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.PossiveisLocais>() {
            public com.roo.viralatas.domain.PossiveisLocais convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), PossiveisLocais.class);
            }
        };
    }
    
    public Converter<Prontuarios, String> ApplicationConversionServiceFactoryBean.getProntuariosToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Prontuarios, java.lang.String>() {
            public String convert(Prontuarios prontuarios) {
                return new StringBuilder().append(prontuarios.getRegistroAntiRabica()).append(' ').append(prontuarios.getRegistroMultipla()).append(' ').append(prontuarios.getRegistroCastracao()).append(' ').append(prontuarios.getControleParasitas()).toString();
            }
        };
    }
    
    public Converter<Integer, Prontuarios> ApplicationConversionServiceFactoryBean.getIdToProntuariosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Prontuarios>() {
            public com.roo.viralatas.domain.Prontuarios convert(java.lang.Integer id) {
                return Prontuarios.findProntuarios(id);
            }
        };
    }
    
    public Converter<String, Prontuarios> ApplicationConversionServiceFactoryBean.getStringToProntuariosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Prontuarios>() {
            public com.roo.viralatas.domain.Prontuarios convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Prontuarios.class);
            }
        };
    }
    
    public Converter<Situacoes, String> ApplicationConversionServiceFactoryBean.getSituacoesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Situacoes, java.lang.String>() {
            public String convert(Situacoes situacoes) {
                return new StringBuilder().append(situacoes.getDescricao()).toString();
            }
        };
    }
    
    public Converter<Integer, Situacoes> ApplicationConversionServiceFactoryBean.getIdToSituacoesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Situacoes>() {
            public com.roo.viralatas.domain.Situacoes convert(java.lang.Integer id) {
                return Situacoes.findSituacoes(id);
            }
        };
    }
    
    public Converter<String, Situacoes> ApplicationConversionServiceFactoryBean.getStringToSituacoesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Situacoes>() {
            public com.roo.viralatas.domain.Situacoes convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Situacoes.class);
            }
        };
    }
    
    public Converter<SolicitacaoAdocoes, String> ApplicationConversionServiceFactoryBean.getSolicitacaoAdocoesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.SolicitacaoAdocoes, java.lang.String>() {
            public String convert(SolicitacaoAdocoes solicitacaoAdocoes) {
                return new StringBuilder().append(solicitacaoAdocoes.getDataSolicitacaoAdocao()).append(' ').append(solicitacaoAdocoes.getDescricao()).append(' ').append(solicitacaoAdocoes.getIdAdotanteAdotante()).toString();
            }
        };
    }
    
    public Converter<Integer, SolicitacaoAdocoes> ApplicationConversionServiceFactoryBean.getIdToSolicitacaoAdocoesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.SolicitacaoAdocoes>() {
            public com.roo.viralatas.domain.SolicitacaoAdocoes convert(java.lang.Integer id) {
                return SolicitacaoAdocoes.findSolicitacaoAdocoes(id);
            }
        };
    }
    
    public Converter<String, SolicitacaoAdocoes> ApplicationConversionServiceFactoryBean.getStringToSolicitacaoAdocoesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.SolicitacaoAdocoes>() {
            public com.roo.viralatas.domain.SolicitacaoAdocoes convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), SolicitacaoAdocoes.class);
            }
        };
    }
    
    public Converter<Status, String> ApplicationConversionServiceFactoryBean.getStatusToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Status, java.lang.String>() {
            public String convert(Status status) {
                return new StringBuilder().append(status.getDescricao()).toString();
            }
        };
    }
    
    public Converter<Integer, Status> ApplicationConversionServiceFactoryBean.getIdToStatusConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Status>() {
            public com.roo.viralatas.domain.Status convert(java.lang.Integer id) {
                return Status.findStatus(id);
            }
        };
    }
    
    public Converter<String, Status> ApplicationConversionServiceFactoryBean.getStringToStatusConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Status>() {
            public com.roo.viralatas.domain.Status convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Status.class);
            }
        };
    }
    
    public Converter<TipoMoradias, String> ApplicationConversionServiceFactoryBean.getTipoMoradiasToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.TipoMoradias, java.lang.String>() {
            public String convert(TipoMoradias tipoMoradias) {
                return new StringBuilder().append(tipoMoradias.getDescricao()).toString();
            }
        };
    }
    
    public Converter<Integer, TipoMoradias> ApplicationConversionServiceFactoryBean.getIdToTipoMoradiasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.TipoMoradias>() {
            public com.roo.viralatas.domain.TipoMoradias convert(java.lang.Integer id) {
                return TipoMoradias.findTipoMoradias(id);
            }
        };
    }
    
    public Converter<String, TipoMoradias> ApplicationConversionServiceFactoryBean.getStringToTipoMoradiasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.TipoMoradias>() {
            public com.roo.viralatas.domain.TipoMoradias convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), TipoMoradias.class);
            }
        };
    }
    
    public Converter<Usuarios, String> ApplicationConversionServiceFactoryBean.getUsuariosToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.roo.viralatas.domain.Usuarios, java.lang.String>() {
            public String convert(Usuarios usuarios) {
                return new StringBuilder().append(usuarios.getNome()).append(' ').append(usuarios.getLogin()).append(' ').append(usuarios.getSenha()).append(' ').append(usuarios.getDataNascimento()).toString();
            }
        };
    }
    
    public Converter<Integer, Usuarios> ApplicationConversionServiceFactoryBean.getIdToUsuariosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.roo.viralatas.domain.Usuarios>() {
            public com.roo.viralatas.domain.Usuarios convert(java.lang.Integer id) {
                return Usuarios.findUsuarios(id);
            }
        };
    }
    
    public Converter<String, Usuarios> ApplicationConversionServiceFactoryBean.getStringToUsuariosConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.roo.viralatas.domain.Usuarios>() {
            public com.roo.viralatas.domain.Usuarios convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Usuarios.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getAcompanhamentosToStringConverter());
        registry.addConverter(getIdToAcompanhamentosConverter());
        registry.addConverter(getStringToAcompanhamentosConverter());
        registry.addConverter(getAdotantesToStringConverter());
        registry.addConverter(getIdToAdotantesConverter());
        registry.addConverter(getStringToAdotantesConverter());
        registry.addConverter(getAnimaisToStringConverter());
        registry.addConverter(getIdToAnimaisConverter());
        registry.addConverter(getStringToAnimaisConverter());
        registry.addConverter(getCidadesToStringConverter());
        registry.addConverter(getIdToCidadesConverter());
        registry.addConverter(getStringToCidadesConverter());
        registry.addConverter(getEnderecosToStringConverter());
        registry.addConverter(getIdToEnderecosConverter());
        registry.addConverter(getStringToEnderecosConverter());
        registry.addConverter(getFeirasToStringConverter());
        registry.addConverter(getIdToFeirasConverter());
        registry.addConverter(getStringToFeirasConverter());
        registry.addConverter(getHistoricoFeiraAnimaisToStringConverter());
        registry.addConverter(getIdToHistoricoFeiraAnimaisConverter());
        registry.addConverter(getStringToHistoricoFeiraAnimaisConverter());
        registry.addConverter(getMoradiasToStringConverter());
        registry.addConverter(getIdToMoradiasConverter());
        registry.addConverter(getStringToMoradiasConverter());
        registry.addConverter(getPossiveisLocaisToStringConverter());
        registry.addConverter(getIdToPossiveisLocaisConverter());
        registry.addConverter(getStringToPossiveisLocaisConverter());
        registry.addConverter(getProntuariosToStringConverter());
        registry.addConverter(getIdToProntuariosConverter());
        registry.addConverter(getStringToProntuariosConverter());
        registry.addConverter(getSituacoesToStringConverter());
        registry.addConverter(getIdToSituacoesConverter());
        registry.addConverter(getStringToSituacoesConverter());
        registry.addConverter(getSolicitacaoAdocoesToStringConverter());
        registry.addConverter(getIdToSolicitacaoAdocoesConverter());
        registry.addConverter(getStringToSolicitacaoAdocoesConverter());
        registry.addConverter(getStatusToStringConverter());
        registry.addConverter(getIdToStatusConverter());
        registry.addConverter(getStringToStatusConverter());
        registry.addConverter(getTipoMoradiasToStringConverter());
        registry.addConverter(getIdToTipoMoradiasConverter());
        registry.addConverter(getStringToTipoMoradiasConverter());
        registry.addConverter(getUsuariosToStringConverter());
        registry.addConverter(getIdToUsuariosConverter());
        registry.addConverter(getStringToUsuariosConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
