// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.PossiveisLocais;
import com.roo.viralatas.web.CidadesController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CidadesController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String CidadesController.create(@Valid Cidades cidades, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, cidades);
            return "cidadeses/create";
        }
        uiModel.asMap().clear();
        cidades.persist();
        return "redirect:/cidadeses/" + encodeUrlPathSegment(cidades.getIdCidade().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String CidadesController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Cidades());
        return "cidadeses/create";
    }
    
    @RequestMapping(value = "/{idCidade}", produces = "text/html")
    public String CidadesController.show(@PathVariable("idCidade") Integer idCidade, Model uiModel) {
        uiModel.addAttribute("cidades", Cidades.findCidades(idCidade));
        uiModel.addAttribute("itemId", idCidade);
        return "cidadeses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String CidadesController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("cidadeses", Cidades.findCidadesEntries(firstResult, sizeNo));
            float nrOfPages = (float) Cidades.countCidadeses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("cidadeses", Cidades.findAllCidadeses());
        }
        return "cidadeses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String CidadesController.update(@Valid Cidades cidades, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, cidades);
            return "cidadeses/update";
        }
        uiModel.asMap().clear();
        cidades.merge();
        return "redirect:/cidadeses/" + encodeUrlPathSegment(cidades.getIdCidade().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idCidade}", params = "form", produces = "text/html")
    public String CidadesController.updateForm(@PathVariable("idCidade") Integer idCidade, Model uiModel) {
        populateEditForm(uiModel, Cidades.findCidades(idCidade));
        return "cidadeses/update";
    }
    
    @RequestMapping(value = "/{idCidade}", method = RequestMethod.DELETE, produces = "text/html")
    public String CidadesController.delete(@PathVariable("idCidade") Integer idCidade, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Cidades cidades = Cidades.findCidades(idCidade);
        cidades.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/cidadeses";
    }
    
    void CidadesController.populateEditForm(Model uiModel, Cidades cidades) {
        uiModel.addAttribute("cidades", cidades);
        uiModel.addAttribute("enderecoses", Enderecos.findAllEnderecoses());
        uiModel.addAttribute("feirases", Feiras.findAllFeirases());
        uiModel.addAttribute("possiveislocaises", PossiveisLocais.findAllPossiveisLocaises());
    }
    
    String CidadesController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
