// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import com.roo.viralatas.domain.SolicitacaoAdocoes;
import com.roo.viralatas.web.FeirasController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FeirasController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FeirasController.create(@Valid Feiras feiras, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, feiras);
            return "feirases/create";
        }
        uiModel.asMap().clear();
        feiras.persist();
        return "redirect:/feirases/" + encodeUrlPathSegment(feiras.getIdFeira().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FeirasController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Feiras());
        return "feirases/create";
    }
    
    @RequestMapping(value = "/{idFeira}", produces = "text/html")
    public String FeirasController.show(@PathVariable("idFeira") Integer idFeira, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("feiras", Feiras.findFeiras(idFeira));
        uiModel.addAttribute("itemId", idFeira);
        return "feirases/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FeirasController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("feirases", Feiras.findFeirasEntries(firstResult, sizeNo));
            float nrOfPages = (float) Feiras.countFeirases() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("feirases", Feiras.findAllFeirases());
        }
        addDateTimeFormatPatterns(uiModel);
        return "feirases/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FeirasController.update(@Valid Feiras feiras, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, feiras);
            return "feirases/update";
        }
        uiModel.asMap().clear();
        feiras.merge();
        return "redirect:/feirases/" + encodeUrlPathSegment(feiras.getIdFeira().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idFeira}", params = "form", produces = "text/html")
    public String FeirasController.updateForm(@PathVariable("idFeira") Integer idFeira, Model uiModel) {
        populateEditForm(uiModel, Feiras.findFeiras(idFeira));
        return "feirases/update";
    }
    
    @RequestMapping(value = "/{idFeira}", method = RequestMethod.DELETE, produces = "text/html")
    public String FeirasController.delete(@PathVariable("idFeira") Integer idFeira, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Feiras feiras = Feiras.findFeiras(idFeira);
        feiras.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/feirases";
    }
    
    void FeirasController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("feiras_datainicio_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("feiras_dataencerramento_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void FeirasController.populateEditForm(Model uiModel, Feiras feiras) {
        uiModel.addAttribute("feiras", feiras);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("animaises", Animais.findAllAnimaises());
        uiModel.addAttribute("cidadeses", Cidades.findAllCidadeses());
        uiModel.addAttribute("historicofeiraanimaises", HistoricoFeiraAnimais.findAllHistoricoFeiraAnimaises());
        uiModel.addAttribute("solicitacaoadocoeses", SolicitacaoAdocoes.findAllSolicitacaoAdocoeses());
    }
    
    String FeirasController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
