// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import com.roo.viralatas.web.HistoricoFeiraAnimaisController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect HistoricoFeiraAnimaisController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String HistoricoFeiraAnimaisController.create(@Valid HistoricoFeiraAnimais historicoFeiraAnimais, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, historicoFeiraAnimais);
            return "historicofeiraanimaises/create";
        }
        uiModel.asMap().clear();
        historicoFeiraAnimais.persist();
        return "redirect:/historicofeiraanimaises/" + encodeUrlPathSegment(historicoFeiraAnimais.getIdHistoricoFeiraAnimal().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String HistoricoFeiraAnimaisController.createForm(Model uiModel) {
        populateEditForm(uiModel, new HistoricoFeiraAnimais());
        return "historicofeiraanimaises/create";
    }
    
    @RequestMapping(value = "/{idHistoricoFeiraAnimal}", produces = "text/html")
    public String HistoricoFeiraAnimaisController.show(@PathVariable("idHistoricoFeiraAnimal") Integer idHistoricoFeiraAnimal, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("historicofeiraanimais", HistoricoFeiraAnimais.findHistoricoFeiraAnimais(idHistoricoFeiraAnimal));
        uiModel.addAttribute("itemId", idHistoricoFeiraAnimal);
        return "historicofeiraanimaises/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String HistoricoFeiraAnimaisController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("historicofeiraanimaises", HistoricoFeiraAnimais.findHistoricoFeiraAnimaisEntries(firstResult, sizeNo));
            float nrOfPages = (float) HistoricoFeiraAnimais.countHistoricoFeiraAnimaises() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("historicofeiraanimaises", HistoricoFeiraAnimais.findAllHistoricoFeiraAnimaises());
        }
        addDateTimeFormatPatterns(uiModel);
        return "historicofeiraanimaises/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String HistoricoFeiraAnimaisController.update(@Valid HistoricoFeiraAnimais historicoFeiraAnimais, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, historicoFeiraAnimais);
            return "historicofeiraanimaises/update";
        }
        uiModel.asMap().clear();
        historicoFeiraAnimais.merge();
        return "redirect:/historicofeiraanimaises/" + encodeUrlPathSegment(historicoFeiraAnimais.getIdHistoricoFeiraAnimal().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idHistoricoFeiraAnimal}", params = "form", produces = "text/html")
    public String HistoricoFeiraAnimaisController.updateForm(@PathVariable("idHistoricoFeiraAnimal") Integer idHistoricoFeiraAnimal, Model uiModel) {
        populateEditForm(uiModel, HistoricoFeiraAnimais.findHistoricoFeiraAnimais(idHistoricoFeiraAnimal));
        return "historicofeiraanimaises/update";
    }
    
    @RequestMapping(value = "/{idHistoricoFeiraAnimal}", method = RequestMethod.DELETE, produces = "text/html")
    public String HistoricoFeiraAnimaisController.delete(@PathVariable("idHistoricoFeiraAnimal") Integer idHistoricoFeiraAnimal, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        HistoricoFeiraAnimais historicoFeiraAnimais = HistoricoFeiraAnimais.findHistoricoFeiraAnimais(idHistoricoFeiraAnimal);
        historicoFeiraAnimais.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/historicofeiraanimaises";
    }
    
    void HistoricoFeiraAnimaisController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("historicoFeiraAnimais_dataregistro_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void HistoricoFeiraAnimaisController.populateEditForm(Model uiModel, HistoricoFeiraAnimais historicoFeiraAnimais) {
        uiModel.addAttribute("historicoFeiraAnimais", historicoFeiraAnimais);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("animaises", Animais.findAllAnimaises());
        uiModel.addAttribute("feirases", Feiras.findAllFeirases());
    }
    
    String HistoricoFeiraAnimaisController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
