// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Adotantes;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.TipoMoradias;
import com.roo.viralatas.web.MoradiasController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect MoradiasController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String MoradiasController.create(@Valid Moradias moradias, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, moradias);
            return "moradiases/create";
        }
        uiModel.asMap().clear();
        moradias.persist();
        return "redirect:/moradiases/" + encodeUrlPathSegment(moradias.getIdMoradia().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String MoradiasController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Moradias());
        return "moradiases/create";
    }
    
    @RequestMapping(value = "/{idMoradia}", produces = "text/html")
    public String MoradiasController.show(@PathVariable("idMoradia") Integer idMoradia, Model uiModel) {
        uiModel.addAttribute("moradias", Moradias.findMoradias(idMoradia));
        uiModel.addAttribute("itemId", idMoradia);
        return "moradiases/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String MoradiasController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("moradiases", Moradias.findMoradiasEntries(firstResult, sizeNo));
            float nrOfPages = (float) Moradias.countMoradiases() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("moradiases", Moradias.findAllMoradiases());
        }
        return "moradiases/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String MoradiasController.update(@Valid Moradias moradias, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, moradias);
            return "moradiases/update";
        }
        uiModel.asMap().clear();
        moradias.merge();
        return "redirect:/moradiases/" + encodeUrlPathSegment(moradias.getIdMoradia().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idMoradia}", params = "form", produces = "text/html")
    public String MoradiasController.updateForm(@PathVariable("idMoradia") Integer idMoradia, Model uiModel) {
        populateEditForm(uiModel, Moradias.findMoradias(idMoradia));
        return "moradiases/update";
    }
    
    @RequestMapping(value = "/{idMoradia}", method = RequestMethod.DELETE, produces = "text/html")
    public String MoradiasController.delete(@PathVariable("idMoradia") Integer idMoradia, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Moradias moradias = Moradias.findMoradias(idMoradia);
        moradias.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/moradiases";
    }
    
    void MoradiasController.populateEditForm(Model uiModel, Moradias moradias) {
        uiModel.addAttribute("moradias", moradias);
        uiModel.addAttribute("adotanteses", Adotantes.findAllAdotanteses());
        uiModel.addAttribute("enderecoses", Enderecos.findAllEnderecoses());
        uiModel.addAttribute("tipomoradiases", TipoMoradias.findAllTipoMoradiases());
    }
    
    String MoradiasController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
