// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.PossiveisLocais;
import com.roo.viralatas.web.PossiveisLocaisController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect PossiveisLocaisController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String PossiveisLocaisController.create(@Valid PossiveisLocais possiveisLocais, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, possiveisLocais);
            return "possiveislocaises/create";
        }
        uiModel.asMap().clear();
        possiveisLocais.persist();
        return "redirect:/possiveislocaises/" + encodeUrlPathSegment(possiveisLocais.getIdPossiveisLocais().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String PossiveisLocaisController.createForm(Model uiModel) {
        populateEditForm(uiModel, new PossiveisLocais());
        return "possiveislocaises/create";
    }
    
    @RequestMapping(value = "/{idPossiveisLocais}", produces = "text/html")
    public String PossiveisLocaisController.show(@PathVariable("idPossiveisLocais") Integer idPossiveisLocais, Model uiModel) {
        uiModel.addAttribute("possiveislocais", PossiveisLocais.findPossiveisLocais(idPossiveisLocais));
        uiModel.addAttribute("itemId", idPossiveisLocais);
        return "possiveislocaises/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String PossiveisLocaisController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("possiveislocaises", PossiveisLocais.findPossiveisLocaisEntries(firstResult, sizeNo));
            float nrOfPages = (float) PossiveisLocais.countPossiveisLocaises() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("possiveislocaises", PossiveisLocais.findAllPossiveisLocaises());
        }
        return "possiveislocaises/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String PossiveisLocaisController.update(@Valid PossiveisLocais possiveisLocais, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, possiveisLocais);
            return "possiveislocaises/update";
        }
        uiModel.asMap().clear();
        possiveisLocais.merge();
        return "redirect:/possiveislocaises/" + encodeUrlPathSegment(possiveisLocais.getIdPossiveisLocais().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idPossiveisLocais}", params = "form", produces = "text/html")
    public String PossiveisLocaisController.updateForm(@PathVariable("idPossiveisLocais") Integer idPossiveisLocais, Model uiModel) {
        populateEditForm(uiModel, PossiveisLocais.findPossiveisLocais(idPossiveisLocais));
        return "possiveislocaises/update";
    }
    
    @RequestMapping(value = "/{idPossiveisLocais}", method = RequestMethod.DELETE, produces = "text/html")
    public String PossiveisLocaisController.delete(@PathVariable("idPossiveisLocais") Integer idPossiveisLocais, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        PossiveisLocais possiveisLocais = PossiveisLocais.findPossiveisLocais(idPossiveisLocais);
        possiveisLocais.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/possiveislocaises";
    }
    
    void PossiveisLocaisController.populateEditForm(Model uiModel, PossiveisLocais possiveisLocais) {
        uiModel.addAttribute("possiveisLocais", possiveisLocais);
        uiModel.addAttribute("cidadeses", Cidades.findAllCidadeses());
    }
    
    String PossiveisLocaisController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
