// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Situacoes;
import com.roo.viralatas.web.SituacoesController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect SituacoesController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String SituacoesController.create(@Valid Situacoes situacoes, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, situacoes);
            return "situacoeses/create";
        }
        uiModel.asMap().clear();
        situacoes.persist();
        return "redirect:/situacoeses/" + encodeUrlPathSegment(situacoes.getIdSituacao().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String SituacoesController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Situacoes());
        return "situacoeses/create";
    }
    
    @RequestMapping(value = "/{idSituacao}", produces = "text/html")
    public String SituacoesController.show(@PathVariable("idSituacao") Integer idSituacao, Model uiModel) {
        uiModel.addAttribute("situacoes", Situacoes.findSituacoes(idSituacao));
        uiModel.addAttribute("itemId", idSituacao);
        return "situacoeses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String SituacoesController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("situacoeses", Situacoes.findSituacoesEntries(firstResult, sizeNo));
            float nrOfPages = (float) Situacoes.countSituacoeses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("situacoeses", Situacoes.findAllSituacoeses());
        }
        return "situacoeses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String SituacoesController.update(@Valid Situacoes situacoes, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, situacoes);
            return "situacoeses/update";
        }
        uiModel.asMap().clear();
        situacoes.merge();
        return "redirect:/situacoeses/" + encodeUrlPathSegment(situacoes.getIdSituacao().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idSituacao}", params = "form", produces = "text/html")
    public String SituacoesController.updateForm(@PathVariable("idSituacao") Integer idSituacao, Model uiModel) {
        populateEditForm(uiModel, Situacoes.findSituacoes(idSituacao));
        return "situacoeses/update";
    }
    
    @RequestMapping(value = "/{idSituacao}", method = RequestMethod.DELETE, produces = "text/html")
    public String SituacoesController.delete(@PathVariable("idSituacao") Integer idSituacao, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Situacoes situacoes = Situacoes.findSituacoes(idSituacao);
        situacoes.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/situacoeses";
    }
    
    void SituacoesController.populateEditForm(Model uiModel, Situacoes situacoes) {
        uiModel.addAttribute("situacoes", situacoes);
    }
    
    String SituacoesController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
