// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.SolicitacaoAdocoes;
import com.roo.viralatas.domain.Status;
import com.roo.viralatas.web.StatusController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect StatusController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String StatusController.create(@Valid Status status, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, status);
            return "statuses/create";
        }
        uiModel.asMap().clear();
        status.persist();
        return "redirect:/statuses/" + encodeUrlPathSegment(status.getIdstatus().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String StatusController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Status());
        return "statuses/create";
    }
    
    @RequestMapping(value = "/{idstatus}", produces = "text/html")
    public String StatusController.show(@PathVariable("idstatus") Integer idstatus, Model uiModel) {
        uiModel.addAttribute("status", Status.findStatus(idstatus));
        uiModel.addAttribute("itemId", idstatus);
        return "statuses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String StatusController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("statuses", Status.findStatusEntries(firstResult, sizeNo));
            float nrOfPages = (float) Status.countStatuses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("statuses", Status.findAllStatuses());
        }
        return "statuses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String StatusController.update(@Valid Status status, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, status);
            return "statuses/update";
        }
        uiModel.asMap().clear();
        status.merge();
        return "redirect:/statuses/" + encodeUrlPathSegment(status.getIdstatus().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idstatus}", params = "form", produces = "text/html")
    public String StatusController.updateForm(@PathVariable("idstatus") Integer idstatus, Model uiModel) {
        populateEditForm(uiModel, Status.findStatus(idstatus));
        return "statuses/update";
    }
    
    @RequestMapping(value = "/{idstatus}", method = RequestMethod.DELETE, produces = "text/html")
    public String StatusController.delete(@PathVariable("idstatus") Integer idstatus, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Status status = Status.findStatus(idstatus);
        status.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/statuses";
    }
    
    void StatusController.populateEditForm(Model uiModel, Status status) {
        uiModel.addAttribute("status", status);
        uiModel.addAttribute("solicitacaoadocoeses", SolicitacaoAdocoes.findAllSolicitacaoAdocoeses());
    }
    
    String StatusController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
