// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.web;

import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.TipoMoradias;
import com.roo.viralatas.web.TipoMoradiasController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect TipoMoradiasController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String TipoMoradiasController.create(@Valid TipoMoradias tipoMoradias, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, tipoMoradias);
            return "tipomoradiases/create";
        }
        uiModel.asMap().clear();
        tipoMoradias.persist();
        return "redirect:/tipomoradiases/" + encodeUrlPathSegment(tipoMoradias.getIdTipoMoradia().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String TipoMoradiasController.createForm(Model uiModel) {
        populateEditForm(uiModel, new TipoMoradias());
        return "tipomoradiases/create";
    }
    
    @RequestMapping(value = "/{idTipoMoradia}", produces = "text/html")
    public String TipoMoradiasController.show(@PathVariable("idTipoMoradia") Integer idTipoMoradia, Model uiModel) {
        uiModel.addAttribute("tipomoradias", TipoMoradias.findTipoMoradias(idTipoMoradia));
        uiModel.addAttribute("itemId", idTipoMoradia);
        return "tipomoradiases/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String TipoMoradiasController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("tipomoradiases", TipoMoradias.findTipoMoradiasEntries(firstResult, sizeNo));
            float nrOfPages = (float) TipoMoradias.countTipoMoradiases() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("tipomoradiases", TipoMoradias.findAllTipoMoradiases());
        }
        return "tipomoradiases/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String TipoMoradiasController.update(@Valid TipoMoradias tipoMoradias, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, tipoMoradias);
            return "tipomoradiases/update";
        }
        uiModel.asMap().clear();
        tipoMoradias.merge();
        return "redirect:/tipomoradiases/" + encodeUrlPathSegment(tipoMoradias.getIdTipoMoradia().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{idTipoMoradia}", params = "form", produces = "text/html")
    public String TipoMoradiasController.updateForm(@PathVariable("idTipoMoradia") Integer idTipoMoradia, Model uiModel) {
        populateEditForm(uiModel, TipoMoradias.findTipoMoradias(idTipoMoradia));
        return "tipomoradiases/update";
    }
    
    @RequestMapping(value = "/{idTipoMoradia}", method = RequestMethod.DELETE, produces = "text/html")
    public String TipoMoradiasController.delete(@PathVariable("idTipoMoradia") Integer idTipoMoradia, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        TipoMoradias tipoMoradias = TipoMoradias.findTipoMoradias(idTipoMoradia);
        tipoMoradias.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/tipomoradiases";
    }
    
    void TipoMoradiasController.populateEditForm(Model uiModel, TipoMoradias tipoMoradias) {
        uiModel.addAttribute("tipoMoradias", tipoMoradias);
        uiModel.addAttribute("moradiases", Moradias.findAllMoradiases());
    }
    
    String TipoMoradiasController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
