// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Acompanhamentos;
import com.roo.viralatas.domain.Usuarios;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

privileged aspect Acompanhamentos_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "idUsuario_Usuario", referencedColumnName = "idUsuario", nullable = false)
    private Usuarios Acompanhamentos.idUsuarioUsuario;
    
    @Column(name = "idSolicitacaoAdocao_SolicitacaoAdocao")
    @NotNull
    private Integer Acompanhamentos.idSolicitacaoAdocaoSolicitacaoAdocao;
    
    @Column(name = "statusAcompanhamento", length = 15)
    private String Acompanhamentos.statusAcompanhamento;
    
    @Column(name = "comentario")
    private String Acompanhamentos.comentario;
    
    public Usuarios Acompanhamentos.getIdUsuarioUsuario() {
        return idUsuarioUsuario;
    }
    
    public void Acompanhamentos.setIdUsuarioUsuario(Usuarios idUsuarioUsuario) {
        this.idUsuarioUsuario = idUsuarioUsuario;
    }
    
    public Integer Acompanhamentos.getIdSolicitacaoAdocaoSolicitacaoAdocao() {
        return idSolicitacaoAdocaoSolicitacaoAdocao;
    }
    
    public void Acompanhamentos.setIdSolicitacaoAdocaoSolicitacaoAdocao(Integer idSolicitacaoAdocaoSolicitacaoAdocao) {
        this.idSolicitacaoAdocaoSolicitacaoAdocao = idSolicitacaoAdocaoSolicitacaoAdocao;
    }
    
    public String Acompanhamentos.getStatusAcompanhamento() {
        return statusAcompanhamento;
    }
    
    public void Acompanhamentos.setStatusAcompanhamento(String statusAcompanhamento) {
        this.statusAcompanhamento = statusAcompanhamento;
    }
    
    public String Acompanhamentos.getComentario() {
        return comentario;
    }
    
    public void Acompanhamentos.setComentario(String comentario) {
        this.comentario = comentario;
    }
    
}
