// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Adotantes;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Adotantes_Roo_Jpa_Entity {
    
    declare @type: Adotantes: @Entity;
    
    declare @type: Adotantes: @Table(name = "adotantes");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idAdotante")
    private Integer Adotantes.idAdotante;
    
    public Integer Adotantes.getIdAdotante() {
        return this.idAdotante;
    }
    
    public void Adotantes.setIdAdotante(Integer id) {
        this.idAdotante = id;
    }
    
}
