// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Adotantes;
import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.Usuarios;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

privileged aspect Adotantes_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idAdotanteAdotante")
    private Set<Moradias> Adotantes.moradiass;
    
    @ManyToOne
    @JoinColumn(name = "idUsuario_Usuario", referencedColumnName = "idUsuario", nullable = false)
    private Usuarios Adotantes.idUsuarioUsuario;
    
    @Column(name = "rendaFamiliar")
    private Float Adotantes.rendaFamiliar;
    
    @Column(name = "criancasEmCasa")
    private Short Adotantes.criancasEmCasa;
    
    @Column(name = "quantidadeanimais")
    private Short Adotantes.quantidadeanimais;
    
    @Column(name = "reputacao")
    private Short Adotantes.reputacao;
    
    public Set<Moradias> Adotantes.getMoradiass() {
        return moradiass;
    }
    
    public void Adotantes.setMoradiass(Set<Moradias> moradiass) {
        this.moradiass = moradiass;
    }
    
    public Usuarios Adotantes.getIdUsuarioUsuario() {
        return idUsuarioUsuario;
    }
    
    public void Adotantes.setIdUsuarioUsuario(Usuarios idUsuarioUsuario) {
        this.idUsuarioUsuario = idUsuarioUsuario;
    }
    
    public Float Adotantes.getRendaFamiliar() {
        return rendaFamiliar;
    }
    
    public void Adotantes.setRendaFamiliar(Float rendaFamiliar) {
        this.rendaFamiliar = rendaFamiliar;
    }
    
    public Short Adotantes.getCriancasEmCasa() {
        return criancasEmCasa;
    }
    
    public void Adotantes.setCriancasEmCasa(Short criancasEmCasa) {
        this.criancasEmCasa = criancasEmCasa;
    }
    
    public Short Adotantes.getQuantidadeanimais() {
        return quantidadeanimais;
    }
    
    public void Adotantes.setQuantidadeanimais(Short quantidadeanimais) {
        this.quantidadeanimais = quantidadeanimais;
    }
    
    public Short Adotantes.getReputacao() {
        return reputacao;
    }
    
    public void Adotantes.setReputacao(Short reputacao) {
        this.reputacao = reputacao;
    }
    
}
