// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Animais;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Animais_Roo_Jpa_Entity {
    
    declare @type: Animais: @Entity;
    
    declare @type: Animais: @Table(name = "animais");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idAnimal")
    private Integer Animais.idAnimal;
    
    public Integer Animais.getIdAnimal() {
        return this.idAnimal;
    }
    
    public void Animais.setIdAnimal(Integer id) {
        this.idAnimal = id;
    }
    
}
