// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import com.roo.viralatas.domain.Prontuarios;
import com.roo.viralatas.domain.SolicitacaoAdocoes;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Animais_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idAnimalAnimal")
    private Set<HistoricoFeiraAnimais> Animais.historicoFeiraAnimaiss;
    
    @OneToMany(mappedBy = "idAnimalAnimal")
    private Set<Prontuarios> Animais.prontuarioss;
    
    @OneToMany(mappedBy = "idAnimalAnimal")
    private Set<SolicitacaoAdocoes> Animais.solicitacaoAdocoeses;
    
    @ManyToOne
    @JoinColumn(name = "idFeira_Feira", referencedColumnName = "idFeira")
    private Feiras Animais.idFeiraFeira;
    
    @Column(name = "nome", length = 45)
    private String Animais.nome;
    
    @Column(name = "dataNascimento")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Animais.dataNascimento;
    
    @Column(name = "raca", length = 45)
    private String Animais.raca;
    
    @Column(name = "cor", length = 25)
    private String Animais.cor;
    
    @Column(name = "especie", length = 45)
    private String Animais.especie;
    
    @Column(name = "pelagem", length = 45)
    private String Animais.pelagem;
    
    @Column(name = "deformidade")
    private Boolean Animais.deformidade;
    
    @Column(name = "porte", length = 10)
    private String Animais.porte;
    
    @Column(name = "resenha")
    private String Animais.resenha;
    
    @Column(name = "dataCadastro")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Animais.dataCadastro;
    
    @Column(name = "foto", length = 100)
    private String Animais.foto;
    
    @Column(name = "localidadeLongitude")
    private Double Animais.localidadeLongitude;
    
    @Column(name = "localidadeLatitude")
    private Double Animais.localidadeLatitude;
    
    @Column(name = "idSituacao_Situacao")
    private Integer Animais.idSituacaoSituacao;
    
    @Column(name = "codigoAnimal", length = 40, unique = true)
    private String Animais.codigoAnimal;
    
    public Set<HistoricoFeiraAnimais> Animais.getHistoricoFeiraAnimaiss() {
        return historicoFeiraAnimaiss;
    }
    
    public void Animais.setHistoricoFeiraAnimaiss(Set<HistoricoFeiraAnimais> historicoFeiraAnimaiss) {
        this.historicoFeiraAnimaiss = historicoFeiraAnimaiss;
    }
    
    public Set<Prontuarios> Animais.getProntuarioss() {
        return prontuarioss;
    }
    
    public void Animais.setProntuarioss(Set<Prontuarios> prontuarioss) {
        this.prontuarioss = prontuarioss;
    }
    
    public Set<SolicitacaoAdocoes> Animais.getSolicitacaoAdocoeses() {
        return solicitacaoAdocoeses;
    }
    
    public void Animais.setSolicitacaoAdocoeses(Set<SolicitacaoAdocoes> solicitacaoAdocoeses) {
        this.solicitacaoAdocoeses = solicitacaoAdocoeses;
    }
    
    public Feiras Animais.getIdFeiraFeira() {
        return idFeiraFeira;
    }
    
    public void Animais.setIdFeiraFeira(Feiras idFeiraFeira) {
        this.idFeiraFeira = idFeiraFeira;
    }
    
    public String Animais.getNome() {
        return nome;
    }
    
    public void Animais.setNome(String nome) {
        this.nome = nome;
    }
    
    public Date Animais.getDataNascimento() {
        return dataNascimento;
    }
    
    public void Animais.setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    
    public String Animais.getRaca() {
        return raca;
    }
    
    public void Animais.setRaca(String raca) {
        this.raca = raca;
    }
    
    public String Animais.getCor() {
        return cor;
    }
    
    public void Animais.setCor(String cor) {
        this.cor = cor;
    }
    
    public String Animais.getEspecie() {
        return especie;
    }
    
    public void Animais.setEspecie(String especie) {
        this.especie = especie;
    }
    
    public String Animais.getPelagem() {
        return pelagem;
    }
    
    public void Animais.setPelagem(String pelagem) {
        this.pelagem = pelagem;
    }
    
    public Boolean Animais.getDeformidade() {
        return deformidade;
    }
    
    public void Animais.setDeformidade(Boolean deformidade) {
        this.deformidade = deformidade;
    }
    
    public String Animais.getPorte() {
        return porte;
    }
    
    public void Animais.setPorte(String porte) {
        this.porte = porte;
    }
    
    public String Animais.getResenha() {
        return resenha;
    }
    
    public void Animais.setResenha(String resenha) {
        this.resenha = resenha;
    }
    
    public Date Animais.getDataCadastro() {
        return dataCadastro;
    }
    
    public void Animais.setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    
    public String Animais.getFoto() {
        return foto;
    }
    
    public void Animais.setFoto(String foto) {
        this.foto = foto;
    }
    
    public Double Animais.getLocalidadeLongitude() {
        return localidadeLongitude;
    }
    
    public void Animais.setLocalidadeLongitude(Double localidadeLongitude) {
        this.localidadeLongitude = localidadeLongitude;
    }
    
    public Double Animais.getLocalidadeLatitude() {
        return localidadeLatitude;
    }
    
    public void Animais.setLocalidadeLatitude(Double localidadeLatitude) {
        this.localidadeLatitude = localidadeLatitude;
    }
    
    public Integer Animais.getIdSituacaoSituacao() {
        return idSituacaoSituacao;
    }
    
    public void Animais.setIdSituacaoSituacao(Integer idSituacaoSituacao) {
        this.idSituacaoSituacao = idSituacaoSituacao;
    }
    
    public String Animais.getCodigoAnimal() {
        return codigoAnimal;
    }
    
    public void Animais.setCodigoAnimal(String codigoAnimal) {
        this.codigoAnimal = codigoAnimal;
    }
    
}
