// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Cidades;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Cidades_Roo_Jpa_Entity {
    
    declare @type: Cidades: @Entity;
    
    declare @type: Cidades: @Table(name = "cidades");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idCidade")
    private Integer Cidades.idCidade;
    
    public Integer Cidades.getIdCidade() {
        return this.idCidade;
    }
    
    public void Cidades.setIdCidade(Integer id) {
        this.idCidade = id;
    }
    
}
