// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Cidades;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Cidades_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Cidades.entityManager;
    
    public static final EntityManager Cidades.entityManager() {
        EntityManager em = new Cidades().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Cidades.countCidadeses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Cidades o", Long.class).getSingleResult();
    }
    
    public static List<Cidades> Cidades.findAllCidadeses() {
        return entityManager().createQuery("SELECT o FROM Cidades o", Cidades.class).getResultList();
    }
    
    public static Cidades Cidades.findCidades(Integer idCidade) {
        if (idCidade == null) return null;
        return entityManager().find(Cidades.class, idCidade);
    }
    
    public static List<Cidades> Cidades.findCidadesEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Cidades o", Cidades.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Cidades.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Cidades.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Cidades attached = Cidades.findCidades(this.idCidade);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Cidades.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Cidades.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Cidades Cidades.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Cidades merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
