// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.PossiveisLocais;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;

privileged aspect Cidades_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idCidadeCidade")
    private Set<Enderecos> Cidades.enderecoss;
    
    @OneToMany(mappedBy = "idCidadeCidade")
    private Set<Feiras> Cidades.feirass;
    
    @OneToMany(mappedBy = "idCidadeCidade")
    private Set<PossiveisLocais> Cidades.possiveisLocaiss;
    
    @Column(name = "nome", length = 45)
    private String Cidades.nome;
    
    @Column(name = "estado", length = 2)
    private String Cidades.estado;
    
    public Set<Enderecos> Cidades.getEnderecoss() {
        return enderecoss;
    }
    
    public void Cidades.setEnderecoss(Set<Enderecos> enderecoss) {
        this.enderecoss = enderecoss;
    }
    
    public Set<Feiras> Cidades.getFeirass() {
        return feirass;
    }
    
    public void Cidades.setFeirass(Set<Feiras> feirass) {
        this.feirass = feirass;
    }
    
    public Set<PossiveisLocais> Cidades.getPossiveisLocaiss() {
        return possiveisLocaiss;
    }
    
    public void Cidades.setPossiveisLocaiss(Set<PossiveisLocais> possiveisLocaiss) {
        this.possiveisLocaiss = possiveisLocaiss;
    }
    
    public String Cidades.getNome() {
        return nome;
    }
    
    public void Cidades.setNome(String nome) {
        this.nome = nome;
    }
    
    public String Cidades.getEstado() {
        return estado;
    }
    
    public void Cidades.setEstado(String estado) {
        this.estado = estado;
    }
    
}
