// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.Usuarios;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

privileged aspect Enderecos_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idEnderecoEndereco")
    private Set<Moradias> Enderecos.moradiass;
    
    @ManyToOne
    @JoinColumn(name = "idUsuario_Usuario", referencedColumnName = "idUsuario", nullable = false)
    private Usuarios Enderecos.idUsuarioUsuario;
    
    @ManyToOne
    @JoinColumn(name = "idCidade_Cidade", referencedColumnName = "idCidade", nullable = false)
    private Cidades Enderecos.idCidadeCidade;
    
    @Column(name = "rua", length = 45)
    private String Enderecos.rua;
    
    @Column(name = "numero")
    private Short Enderecos.numero;
    
    @Column(name = "complemento", length = 75)
    private String Enderecos.complemento;
    
    @Column(name = "cep")
    private Long Enderecos.cep;
    
    @Column(name = "areaMoradia")
    private Float Enderecos.areaMoradia;
    
    @Column(name = "tipoEndereco", length = 6)
    private String Enderecos.tipoEndereco;
    
    @Column(name = "bairro", length = 45)
    private String Enderecos.bairro;
    
    @Column(name = "telefone", length = 45)
    private String Enderecos.telefone;
    
    @Column(name = "ativo")
    private Boolean Enderecos.ativo;
    
    public Set<Moradias> Enderecos.getMoradiass() {
        return moradiass;
    }
    
    public void Enderecos.setMoradiass(Set<Moradias> moradiass) {
        this.moradiass = moradiass;
    }
    
    public Usuarios Enderecos.getIdUsuarioUsuario() {
        return idUsuarioUsuario;
    }
    
    public void Enderecos.setIdUsuarioUsuario(Usuarios idUsuarioUsuario) {
        this.idUsuarioUsuario = idUsuarioUsuario;
    }
    
    public Cidades Enderecos.getIdCidadeCidade() {
        return idCidadeCidade;
    }
    
    public void Enderecos.setIdCidadeCidade(Cidades idCidadeCidade) {
        this.idCidadeCidade = idCidadeCidade;
    }
    
    public String Enderecos.getRua() {
        return rua;
    }
    
    public void Enderecos.setRua(String rua) {
        this.rua = rua;
    }
    
    public Short Enderecos.getNumero() {
        return numero;
    }
    
    public void Enderecos.setNumero(Short numero) {
        this.numero = numero;
    }
    
    public String Enderecos.getComplemento() {
        return complemento;
    }
    
    public void Enderecos.setComplemento(String complemento) {
        this.complemento = complemento;
    }
    
    public Long Enderecos.getCep() {
        return cep;
    }
    
    public void Enderecos.setCep(Long cep) {
        this.cep = cep;
    }
    
    public Float Enderecos.getAreaMoradia() {
        return areaMoradia;
    }
    
    public void Enderecos.setAreaMoradia(Float areaMoradia) {
        this.areaMoradia = areaMoradia;
    }
    
    public String Enderecos.getTipoEndereco() {
        return tipoEndereco;
    }
    
    public void Enderecos.setTipoEndereco(String tipoEndereco) {
        this.tipoEndereco = tipoEndereco;
    }
    
    public String Enderecos.getBairro() {
        return bairro;
    }
    
    public void Enderecos.setBairro(String bairro) {
        this.bairro = bairro;
    }
    
    public String Enderecos.getTelefone() {
        return telefone;
    }
    
    public void Enderecos.setTelefone(String telefone) {
        this.telefone = telefone;
    }
    
    public Boolean Enderecos.getAtivo() {
        return ativo;
    }
    
    public void Enderecos.setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }
    
}
