// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Cidades;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import com.roo.viralatas.domain.SolicitacaoAdocoes;
import java.util.Calendar;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Feiras_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idFeiraFeira")
    private Set<Animais> Feiras.animaiss;
    
    @OneToMany(mappedBy = "idFeiraFeira")
    private Set<HistoricoFeiraAnimais> Feiras.historicoFeiraAnimaiss;
    
    @OneToMany(mappedBy = "idFeiraFeira")
    private Set<SolicitacaoAdocoes> Feiras.solicitacaoAdocoeses;
    
    @ManyToOne
    @JoinColumn(name = "idCidade_Cidade", referencedColumnName = "idCidade")
    private Cidades Feiras.idCidadeCidade;
    
    @Column(name = "nomeFeira", length = 45)
    private String Feiras.nomeFeira;
    
    @Column(name = "dataInicio")
    @NotNull
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "MM")
    private Calendar Feiras.dataInicio;
    
    @Column(name = "dataEncerramento")
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "MM")
    private Calendar Feiras.dataEncerramento;
    
    @Column(name = "numeroanimais")
    private Short Feiras.numeroanimais;
    
    @Column(name = "animaisAdotados")
    private Short Feiras.animaisAdotados;
    
    @Column(name = "longitude")
    private Double Feiras.longitude;
    
    @Column(name = "latitude")
    private Double Feiras.latitude;
    
    @Column(name = "idpossiveis_locais_PossiveisLocais")
    private Integer Feiras.idpossiveisLocaisPossiveisLocais;
    
    @Column(name = "ativo")
    private Boolean Feiras.ativo;
    
    public Set<Animais> Feiras.getAnimaiss() {
        return animaiss;
    }
    
    public void Feiras.setAnimaiss(Set<Animais> animaiss) {
        this.animaiss = animaiss;
    }
    
    public Set<HistoricoFeiraAnimais> Feiras.getHistoricoFeiraAnimaiss() {
        return historicoFeiraAnimaiss;
    }
    
    public void Feiras.setHistoricoFeiraAnimaiss(Set<HistoricoFeiraAnimais> historicoFeiraAnimaiss) {
        this.historicoFeiraAnimaiss = historicoFeiraAnimaiss;
    }
    
    public Set<SolicitacaoAdocoes> Feiras.getSolicitacaoAdocoeses() {
        return solicitacaoAdocoeses;
    }
    
    public void Feiras.setSolicitacaoAdocoeses(Set<SolicitacaoAdocoes> solicitacaoAdocoeses) {
        this.solicitacaoAdocoeses = solicitacaoAdocoeses;
    }
    
    public Cidades Feiras.getIdCidadeCidade() {
        return idCidadeCidade;
    }
    
    public void Feiras.setIdCidadeCidade(Cidades idCidadeCidade) {
        this.idCidadeCidade = idCidadeCidade;
    }
    
    public String Feiras.getNomeFeira() {
        return nomeFeira;
    }
    
    public void Feiras.setNomeFeira(String nomeFeira) {
        this.nomeFeira = nomeFeira;
    }
    
    public Calendar Feiras.getDataInicio() {
        return dataInicio;
    }
    
    public void Feiras.setDataInicio(Calendar dataInicio) {
        this.dataInicio = dataInicio;
    }
    
    public Calendar Feiras.getDataEncerramento() {
        return dataEncerramento;
    }
    
    public void Feiras.setDataEncerramento(Calendar dataEncerramento) {
        this.dataEncerramento = dataEncerramento;
    }
    
    public Short Feiras.getNumeroanimais() {
        return numeroanimais;
    }
    
    public void Feiras.setNumeroanimais(Short numeroanimais) {
        this.numeroanimais = numeroanimais;
    }
    
    public Short Feiras.getAnimaisAdotados() {
        return animaisAdotados;
    }
    
    public void Feiras.setAnimaisAdotados(Short animaisAdotados) {
        this.animaisAdotados = animaisAdotados;
    }
    
    public Double Feiras.getLongitude() {
        return longitude;
    }
    
    public void Feiras.setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    
    public Double Feiras.getLatitude() {
        return latitude;
    }
    
    public void Feiras.setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    
    public Integer Feiras.getIdpossiveisLocaisPossiveisLocais() {
        return idpossiveisLocaisPossiveisLocais;
    }
    
    public void Feiras.setIdpossiveisLocaisPossiveisLocais(Integer idpossiveisLocaisPossiveisLocais) {
        this.idpossiveisLocaisPossiveisLocais = idpossiveisLocaisPossiveisLocais;
    }
    
    public Boolean Feiras.getAtivo() {
        return ativo;
    }
    
    public void Feiras.setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }
    
}
