// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Feiras;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Feiras_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Feiras.entityManager;
    
    public static final EntityManager Feiras.entityManager() {
        EntityManager em = new Feiras().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Feiras.countFeirases() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Feiras o", Long.class).getSingleResult();
    }
    
    public static List<Feiras> Feiras.findAllFeirases() {
        return entityManager().createQuery("SELECT o FROM Feiras o", Feiras.class).getResultList();
    }
    
    public static Feiras Feiras.findFeiras(Integer idFeira) {
        if (idFeira == null) return null;
        return entityManager().find(Feiras.class, idFeira);
    }
    
    public static List<Feiras> Feiras.findFeirasEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Feiras o", Feiras.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Feiras.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Feiras.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Feiras attached = Feiras.findFeiras(this.idFeira);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Feiras.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Feiras.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Feiras Feiras.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Feiras merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
