// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect HistoricoFeiraAnimais_Roo_Jpa_Entity {
    
    declare @type: HistoricoFeiraAnimais: @Entity;
    
    declare @type: HistoricoFeiraAnimais: @Table(name = "historico_feira_animais");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idHistoricoFeiraAnimal")
    private Integer HistoricoFeiraAnimais.idHistoricoFeiraAnimal;
    
    public Integer HistoricoFeiraAnimais.getIdHistoricoFeiraAnimal() {
        return this.idHistoricoFeiraAnimal;
    }
    
    public void HistoricoFeiraAnimais.setIdHistoricoFeiraAnimal(Integer id) {
        this.idHistoricoFeiraAnimal = id;
    }
    
}
