// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.HistoricoFeiraAnimais;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HistoricoFeiraAnimais_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager HistoricoFeiraAnimais.entityManager;
    
    public static final EntityManager HistoricoFeiraAnimais.entityManager() {
        EntityManager em = new HistoricoFeiraAnimais().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long HistoricoFeiraAnimais.countHistoricoFeiraAnimaises() {
        return entityManager().createQuery("SELECT COUNT(o) FROM HistoricoFeiraAnimais o", Long.class).getSingleResult();
    }
    
    public static List<HistoricoFeiraAnimais> HistoricoFeiraAnimais.findAllHistoricoFeiraAnimaises() {
        return entityManager().createQuery("SELECT o FROM HistoricoFeiraAnimais o", HistoricoFeiraAnimais.class).getResultList();
    }
    
    public static HistoricoFeiraAnimais HistoricoFeiraAnimais.findHistoricoFeiraAnimais(Integer idHistoricoFeiraAnimal) {
        if (idHistoricoFeiraAnimal == null) return null;
        return entityManager().find(HistoricoFeiraAnimais.class, idHistoricoFeiraAnimal);
    }
    
    public static List<HistoricoFeiraAnimais> HistoricoFeiraAnimais.findHistoricoFeiraAnimaisEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM HistoricoFeiraAnimais o", HistoricoFeiraAnimais.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void HistoricoFeiraAnimais.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void HistoricoFeiraAnimais.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            HistoricoFeiraAnimais attached = HistoricoFeiraAnimais.findHistoricoFeiraAnimais(this.idHistoricoFeiraAnimal);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void HistoricoFeiraAnimais.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void HistoricoFeiraAnimais.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public HistoricoFeiraAnimais HistoricoFeiraAnimais.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        HistoricoFeiraAnimais merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
