// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Moradias;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Moradias_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Moradias.entityManager;
    
    public static final EntityManager Moradias.entityManager() {
        EntityManager em = new Moradias().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Moradias.countMoradiases() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Moradias o", Long.class).getSingleResult();
    }
    
    public static List<Moradias> Moradias.findAllMoradiases() {
        return entityManager().createQuery("SELECT o FROM Moradias o", Moradias.class).getResultList();
    }
    
    public static Moradias Moradias.findMoradias(Integer idMoradia) {
        if (idMoradia == null) return null;
        return entityManager().find(Moradias.class, idMoradia);
    }
    
    public static List<Moradias> Moradias.findMoradiasEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Moradias o", Moradias.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Moradias.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Moradias.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Moradias attached = Moradias.findMoradias(this.idMoradia);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Moradias.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Moradias.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Moradias Moradias.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Moradias merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
