// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Adotantes;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.TipoMoradias;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

privileged aspect Moradias_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "idAdotante_Adotante", referencedColumnName = "idAdotante", nullable = false)
    private Adotantes Moradias.idAdotanteAdotante;
    
    @ManyToOne
    @JoinColumn(name = "idEndereco_Endereco", referencedColumnName = "idEndereco")
    private Enderecos Moradias.idEnderecoEndereco;
    
    @ManyToOne
    @JoinColumn(name = "idTipoMoradia_TipoMoradia", referencedColumnName = "idTipoMoradia")
    private TipoMoradias Moradias.idTipoMoradiaTipoMoradia;
    
    public Adotantes Moradias.getIdAdotanteAdotante() {
        return idAdotanteAdotante;
    }
    
    public void Moradias.setIdAdotanteAdotante(Adotantes idAdotanteAdotante) {
        this.idAdotanteAdotante = idAdotanteAdotante;
    }
    
    public Enderecos Moradias.getIdEnderecoEndereco() {
        return idEnderecoEndereco;
    }
    
    public void Moradias.setIdEnderecoEndereco(Enderecos idEnderecoEndereco) {
        this.idEnderecoEndereco = idEnderecoEndereco;
    }
    
    public TipoMoradias Moradias.getIdTipoMoradiaTipoMoradia() {
        return idTipoMoradiaTipoMoradia;
    }
    
    public void Moradias.setIdTipoMoradiaTipoMoradia(TipoMoradias idTipoMoradiaTipoMoradia) {
        this.idTipoMoradiaTipoMoradia = idTipoMoradiaTipoMoradia;
    }
    
}
