// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.PossiveisLocais;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PossiveisLocais_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager PossiveisLocais.entityManager;
    
    public static final EntityManager PossiveisLocais.entityManager() {
        EntityManager em = new PossiveisLocais().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long PossiveisLocais.countPossiveisLocaises() {
        return entityManager().createQuery("SELECT COUNT(o) FROM PossiveisLocais o", Long.class).getSingleResult();
    }
    
    public static List<PossiveisLocais> PossiveisLocais.findAllPossiveisLocaises() {
        return entityManager().createQuery("SELECT o FROM PossiveisLocais o", PossiveisLocais.class).getResultList();
    }
    
    public static PossiveisLocais PossiveisLocais.findPossiveisLocais(Integer idPossiveisLocais) {
        if (idPossiveisLocais == null) return null;
        return entityManager().find(PossiveisLocais.class, idPossiveisLocais);
    }
    
    public static List<PossiveisLocais> PossiveisLocais.findPossiveisLocaisEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM PossiveisLocais o", PossiveisLocais.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void PossiveisLocais.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void PossiveisLocais.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            PossiveisLocais attached = PossiveisLocais.findPossiveisLocais(this.idPossiveisLocais);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void PossiveisLocais.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void PossiveisLocais.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public PossiveisLocais PossiveisLocais.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        PossiveisLocais merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
