// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.PossiveisLocais;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect PossiveisLocais_Roo_Jpa_Entity {
    
    declare @type: PossiveisLocais: @Entity;
    
    declare @type: PossiveisLocais: @Table(name = "possiveis_locais");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idPossiveisLocais")
    private Integer PossiveisLocais.idPossiveisLocais;
    
    public Integer PossiveisLocais.getIdPossiveisLocais() {
        return this.idPossiveisLocais;
    }
    
    public void PossiveisLocais.setIdPossiveisLocais(Integer id) {
        this.idPossiveisLocais = id;
    }
    
}
