// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Prontuarios;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Prontuarios_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "idAnimal_Animal", referencedColumnName = "idAnimal", nullable = false)
    private Animais Prontuarios.idAnimalAnimal;
    
    @Column(name = "registroAntiRabica", length = 100)
    private String Prontuarios.registroAntiRabica;
    
    @Column(name = "registroMultipla", length = 100)
    private String Prontuarios.registroMultipla;
    
    @Column(name = "registroCastracao", length = 100)
    private String Prontuarios.registroCastracao;
    
    @Column(name = "controleParasitas", length = 100)
    private String Prontuarios.controleParasitas;
    
    @Column(name = "dataControleParasitas")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Prontuarios.dataControleParasitas;
    
    @Column(name = "veterinarioResponsavelControleParasitas", length = 45)
    private String Prontuarios.veterinarioResponsavelControleParasitas;
    
    @Column(name = "dataRegistro")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Prontuarios.dataRegistro;
    
    @Column(name = "patologia", length = 100)
    private String Prontuarios.patologia;
    
    @Column(name = "deformidade")
    private Boolean Prontuarios.deformidade;
    
    public Animais Prontuarios.getIdAnimalAnimal() {
        return idAnimalAnimal;
    }
    
    public void Prontuarios.setIdAnimalAnimal(Animais idAnimalAnimal) {
        this.idAnimalAnimal = idAnimalAnimal;
    }
    
    public String Prontuarios.getRegistroAntiRabica() {
        return registroAntiRabica;
    }
    
    public void Prontuarios.setRegistroAntiRabica(String registroAntiRabica) {
        this.registroAntiRabica = registroAntiRabica;
    }
    
    public String Prontuarios.getRegistroMultipla() {
        return registroMultipla;
    }
    
    public void Prontuarios.setRegistroMultipla(String registroMultipla) {
        this.registroMultipla = registroMultipla;
    }
    
    public String Prontuarios.getRegistroCastracao() {
        return registroCastracao;
    }
    
    public void Prontuarios.setRegistroCastracao(String registroCastracao) {
        this.registroCastracao = registroCastracao;
    }
    
    public String Prontuarios.getControleParasitas() {
        return controleParasitas;
    }
    
    public void Prontuarios.setControleParasitas(String controleParasitas) {
        this.controleParasitas = controleParasitas;
    }
    
    public Date Prontuarios.getDataControleParasitas() {
        return dataControleParasitas;
    }
    
    public void Prontuarios.setDataControleParasitas(Date dataControleParasitas) {
        this.dataControleParasitas = dataControleParasitas;
    }
    
    public String Prontuarios.getVeterinarioResponsavelControleParasitas() {
        return veterinarioResponsavelControleParasitas;
    }
    
    public void Prontuarios.setVeterinarioResponsavelControleParasitas(String veterinarioResponsavelControleParasitas) {
        this.veterinarioResponsavelControleParasitas = veterinarioResponsavelControleParasitas;
    }
    
    public Date Prontuarios.getDataRegistro() {
        return dataRegistro;
    }
    
    public void Prontuarios.setDataRegistro(Date dataRegistro) {
        this.dataRegistro = dataRegistro;
    }
    
    public String Prontuarios.getPatologia() {
        return patologia;
    }
    
    public void Prontuarios.setPatologia(String patologia) {
        this.patologia = patologia;
    }
    
    public Boolean Prontuarios.getDeformidade() {
        return deformidade;
    }
    
    public void Prontuarios.setDeformidade(Boolean deformidade) {
        this.deformidade = deformidade;
    }
    
}
