// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Prontuarios;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Prontuarios_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Prontuarios.entityManager;
    
    public static final EntityManager Prontuarios.entityManager() {
        EntityManager em = new Prontuarios().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Prontuarios.countProntuarioses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Prontuarios o", Long.class).getSingleResult();
    }
    
    public static List<Prontuarios> Prontuarios.findAllProntuarioses() {
        return entityManager().createQuery("SELECT o FROM Prontuarios o", Prontuarios.class).getResultList();
    }
    
    public static Prontuarios Prontuarios.findProntuarios(Integer idProntuario) {
        if (idProntuario == null) return null;
        return entityManager().find(Prontuarios.class, idProntuario);
    }
    
    public static List<Prontuarios> Prontuarios.findProntuariosEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Prontuarios o", Prontuarios.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Prontuarios.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Prontuarios.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Prontuarios attached = Prontuarios.findProntuarios(this.idProntuario);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Prontuarios.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Prontuarios.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Prontuarios Prontuarios.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Prontuarios merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
