// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Prontuarios;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Prontuarios_Roo_Jpa_Entity {
    
    declare @type: Prontuarios: @Entity;
    
    declare @type: Prontuarios: @Table(name = "prontuarios");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idProntuario")
    private Integer Prontuarios.idProntuario;
    
    public Integer Prontuarios.getIdProntuario() {
        return this.idProntuario;
    }
    
    public void Prontuarios.setIdProntuario(Integer id) {
        this.idProntuario = id;
    }
    
}
