// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Situacoes;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Situacoes_Roo_Jpa_Entity {
    
    declare @type: Situacoes: @Entity;
    
    declare @type: Situacoes: @Table(name = "situacoes");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idSituacao")
    private Integer Situacoes.idSituacao;
    
    public Integer Situacoes.getIdSituacao() {
        return this.idSituacao;
    }
    
    public void Situacoes.setIdSituacao(Integer id) {
        this.idSituacao = id;
    }
    
}
