// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Situacoes;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Situacoes_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Situacoes.entityManager;
    
    public static final EntityManager Situacoes.entityManager() {
        EntityManager em = new Situacoes().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Situacoes.countSituacoeses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Situacoes o", Long.class).getSingleResult();
    }
    
    public static List<Situacoes> Situacoes.findAllSituacoeses() {
        return entityManager().createQuery("SELECT o FROM Situacoes o", Situacoes.class).getResultList();
    }
    
    public static Situacoes Situacoes.findSituacoes(Integer idSituacao) {
        if (idSituacao == null) return null;
        return entityManager().find(Situacoes.class, idSituacao);
    }
    
    public static List<Situacoes> Situacoes.findSituacoesEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Situacoes o", Situacoes.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Situacoes.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Situacoes.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Situacoes attached = Situacoes.findSituacoes(this.idSituacao);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Situacoes.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Situacoes.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Situacoes Situacoes.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Situacoes merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
