// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.SolicitacaoAdocoes;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect SolicitacaoAdocoes_Roo_Jpa_Entity {
    
    declare @type: SolicitacaoAdocoes: @Entity;
    
    declare @type: SolicitacaoAdocoes: @Table(name = "solicitacao_adocoes");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idSolicitacaoAdocao")
    private Integer SolicitacaoAdocoes.idSolicitacaoAdocao;
    
    public Integer SolicitacaoAdocoes.getIdSolicitacaoAdocao() {
        return this.idSolicitacaoAdocao;
    }
    
    public void SolicitacaoAdocoes.setIdSolicitacaoAdocao(Integer id) {
        this.idSolicitacaoAdocao = id;
    }
    
}
