// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Animais;
import com.roo.viralatas.domain.Feiras;
import com.roo.viralatas.domain.SolicitacaoAdocoes;
import com.roo.viralatas.domain.Status;
import com.roo.viralatas.domain.Usuarios;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect SolicitacaoAdocoes_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "idUsuario_Usuario", referencedColumnName = "idUsuario")
    private Usuarios SolicitacaoAdocoes.idUsuarioUsuario;
    
    @ManyToOne
    @JoinColumn(name = "idFeira_Feira", referencedColumnName = "idFeira")
    private Feiras SolicitacaoAdocoes.idFeiraFeira;
    
    @ManyToOne
    @JoinColumn(name = "idAnimal_Animal", referencedColumnName = "idAnimal")
    private Animais SolicitacaoAdocoes.idAnimalAnimal;
    
    @ManyToOne
    @JoinColumn(name = "idstatus_status", referencedColumnName = "idstatus")
    private Status SolicitacaoAdocoes.idstatusStatus;
    
    @Column(name = "dataSolicitacaoAdocao")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date SolicitacaoAdocoes.dataSolicitacaoAdocao;
    
    @Column(name = "descricao")
    private String SolicitacaoAdocoes.descricao;
    
    @Column(name = "idAdotante_Adotante")
    private Integer SolicitacaoAdocoes.idAdotanteAdotante;
    
    public Usuarios SolicitacaoAdocoes.getIdUsuarioUsuario() {
        return idUsuarioUsuario;
    }
    
    public void SolicitacaoAdocoes.setIdUsuarioUsuario(Usuarios idUsuarioUsuario) {
        this.idUsuarioUsuario = idUsuarioUsuario;
    }
    
    public Feiras SolicitacaoAdocoes.getIdFeiraFeira() {
        return idFeiraFeira;
    }
    
    public void SolicitacaoAdocoes.setIdFeiraFeira(Feiras idFeiraFeira) {
        this.idFeiraFeira = idFeiraFeira;
    }
    
    public Animais SolicitacaoAdocoes.getIdAnimalAnimal() {
        return idAnimalAnimal;
    }
    
    public void SolicitacaoAdocoes.setIdAnimalAnimal(Animais idAnimalAnimal) {
        this.idAnimalAnimal = idAnimalAnimal;
    }
    
    public Status SolicitacaoAdocoes.getIdstatusStatus() {
        return idstatusStatus;
    }
    
    public void SolicitacaoAdocoes.setIdstatusStatus(Status idstatusStatus) {
        this.idstatusStatus = idstatusStatus;
    }
    
    public Date SolicitacaoAdocoes.getDataSolicitacaoAdocao() {
        return dataSolicitacaoAdocao;
    }
    
    public void SolicitacaoAdocoes.setDataSolicitacaoAdocao(Date dataSolicitacaoAdocao) {
        this.dataSolicitacaoAdocao = dataSolicitacaoAdocao;
    }
    
    public String SolicitacaoAdocoes.getDescricao() {
        return descricao;
    }
    
    public void SolicitacaoAdocoes.setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    public Integer SolicitacaoAdocoes.getIdAdotanteAdotante() {
        return idAdotanteAdotante;
    }
    
    public void SolicitacaoAdocoes.setIdAdotanteAdotante(Integer idAdotanteAdotante) {
        this.idAdotanteAdotante = idAdotanteAdotante;
    }
    
}
