// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.SolicitacaoAdocoes;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

privileged aspect SolicitacaoAdocoes_Roo_ToString {
    
    public String SolicitacaoAdocoes.toString() {
        return new ReflectionToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).setExcludeFieldNames("idUsuarioUsuario", "idFeiraFeira", "idAnimalAnimal", "idstatusStatus").toString();
    }
    
}
