// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.SolicitacaoAdocoes;
import com.roo.viralatas.domain.Status;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;

privileged aspect Status_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idstatusStatus")
    private Set<SolicitacaoAdocoes> Status.solicitacaoAdocoeses;
    
    @Column(name = "descricao", length = 25)
    private String Status.descricao;
    
    public Set<SolicitacaoAdocoes> Status.getSolicitacaoAdocoeses() {
        return solicitacaoAdocoeses;
    }
    
    public void Status.setSolicitacaoAdocoeses(Set<SolicitacaoAdocoes> solicitacaoAdocoeses) {
        this.solicitacaoAdocoeses = solicitacaoAdocoeses;
    }
    
    public String Status.getDescricao() {
        return descricao;
    }
    
    public void Status.setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
}
