// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Moradias;
import com.roo.viralatas.domain.TipoMoradias;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;

privileged aspect TipoMoradias_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idTipoMoradiaTipoMoradia")
    private Set<Moradias> TipoMoradias.moradiass;
    
    @Column(name = "descricao", length = 25)
    private String TipoMoradias.descricao;
    
    public Set<Moradias> TipoMoradias.getMoradiass() {
        return moradiass;
    }
    
    public void TipoMoradias.setMoradiass(Set<Moradias> moradiass) {
        this.moradiass = moradiass;
    }
    
    public String TipoMoradias.getDescricao() {
        return descricao;
    }
    
    public void TipoMoradias.setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
}
