// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.TipoMoradias;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoMoradias_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager TipoMoradias.entityManager;
    
    public static final EntityManager TipoMoradias.entityManager() {
        EntityManager em = new TipoMoradias().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TipoMoradias.countTipoMoradiases() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TipoMoradias o", Long.class).getSingleResult();
    }
    
    public static List<TipoMoradias> TipoMoradias.findAllTipoMoradiases() {
        return entityManager().createQuery("SELECT o FROM TipoMoradias o", TipoMoradias.class).getResultList();
    }
    
    public static TipoMoradias TipoMoradias.findTipoMoradias(Integer idTipoMoradia) {
        if (idTipoMoradia == null) return null;
        return entityManager().find(TipoMoradias.class, idTipoMoradia);
    }
    
    public static List<TipoMoradias> TipoMoradias.findTipoMoradiasEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TipoMoradias o", TipoMoradias.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void TipoMoradias.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TipoMoradias.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TipoMoradias attached = TipoMoradias.findTipoMoradias(this.idTipoMoradia);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TipoMoradias.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TipoMoradias.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TipoMoradias TipoMoradias.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TipoMoradias merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
