// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.TipoMoradias;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect TipoMoradias_Roo_Jpa_Entity {
    
    declare @type: TipoMoradias: @Entity;
    
    declare @type: TipoMoradias: @Table(name = "tipo_moradias");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idTipoMoradia")
    private Integer TipoMoradias.idTipoMoradia;
    
    public Integer TipoMoradias.getIdTipoMoradia() {
        return this.idTipoMoradia;
    }
    
    public void TipoMoradias.setIdTipoMoradia(Integer id) {
        this.idTipoMoradia = id;
    }
    
}
