// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.viralatas.domain;

import com.roo.viralatas.domain.Acompanhamentos;
import com.roo.viralatas.domain.Adotantes;
import com.roo.viralatas.domain.Enderecos;
import com.roo.viralatas.domain.SolicitacaoAdocoes;
import com.roo.viralatas.domain.Usuarios;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Usuarios_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idUsuarioUsuario")
    private Set<Acompanhamentos> Usuarios.acompanhamentoss;
    
    @OneToMany(mappedBy = "idUsuarioUsuario")
    private Set<Adotantes> Usuarios.adotanteses;
    
    @OneToMany(mappedBy = "idUsuarioUsuario")
    private Set<Enderecos> Usuarios.enderecoss;
    
    @OneToMany(mappedBy = "idUsuarioUsuario")
    private Set<SolicitacaoAdocoes> Usuarios.solicitacaoAdocoeses;
    
    @Column(name = "nome", length = 50)
    private String Usuarios.nome;
    
    @Column(name = "login", length = 50, unique = true)
    private String Usuarios.login;
    
    @Column(name = "senha", length = 100)
    private String Usuarios.senha;
    
    @Column(name = "dataNascimento")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Usuarios.dataNascimento;
    
    @Column(name = "cpfCnpj", length = 14, unique = true)
    private String Usuarios.cpfCnpj;
    
    @Column(name = "emp_nomeFantasia", length = 75)
    private String Usuarios.empNomeFantasia;
    
    @Column(name = "emp_razaoSocial", length = 75)
    private String Usuarios.empRazaoSocial;
    
    @Column(name = "email", length = 100)
    private String Usuarios.email;
    
    @Column(name = "rg", length = 15)
    private String Usuarios.rg;
    
    @Column(name = "tipoAcesso", length = 3)
    private String Usuarios.tipoAcesso;
    
    @Column(name = "tipoPessoa", length = 3)
    private String Usuarios.tipoPessoa;
    
    @Column(name = "telefoneCelular", length = 15)
    private String Usuarios.telefoneCelular;
    
    @Column(name = "foto", length = 100)
    private String Usuarios.foto;
    
    public Set<Acompanhamentos> Usuarios.getAcompanhamentoss() {
        return acompanhamentoss;
    }
    
    public void Usuarios.setAcompanhamentoss(Set<Acompanhamentos> acompanhamentoss) {
        this.acompanhamentoss = acompanhamentoss;
    }
    
    public Set<Adotantes> Usuarios.getAdotanteses() {
        return adotanteses;
    }
    
    public void Usuarios.setAdotanteses(Set<Adotantes> adotanteses) {
        this.adotanteses = adotanteses;
    }
    
    public Set<Enderecos> Usuarios.getEnderecoss() {
        return enderecoss;
    }
    
    public void Usuarios.setEnderecoss(Set<Enderecos> enderecoss) {
        this.enderecoss = enderecoss;
    }
    
    public Set<SolicitacaoAdocoes> Usuarios.getSolicitacaoAdocoeses() {
        return solicitacaoAdocoeses;
    }
    
    public void Usuarios.setSolicitacaoAdocoeses(Set<SolicitacaoAdocoes> solicitacaoAdocoeses) {
        this.solicitacaoAdocoeses = solicitacaoAdocoeses;
    }
    
    public String Usuarios.getNome() {
        return nome;
    }
    
    public void Usuarios.setNome(String nome) {
        this.nome = nome;
    }
    
    public String Usuarios.getLogin() {
        return login;
    }
    
    public void Usuarios.setLogin(String login) {
        this.login = login;
    }
    
    public String Usuarios.getSenha() {
        return senha;
    }
    
    public void Usuarios.setSenha(String senha) {
        this.senha = senha;
    }
    
    public Date Usuarios.getDataNascimento() {
        return dataNascimento;
    }
    
    public void Usuarios.setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    
    public String Usuarios.getCpfCnpj() {
        return cpfCnpj;
    }
    
    public void Usuarios.setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }
    
    public String Usuarios.getEmpNomeFantasia() {
        return empNomeFantasia;
    }
    
    public void Usuarios.setEmpNomeFantasia(String empNomeFantasia) {
        this.empNomeFantasia = empNomeFantasia;
    }
    
    public String Usuarios.getEmpRazaoSocial() {
        return empRazaoSocial;
    }
    
    public void Usuarios.setEmpRazaoSocial(String empRazaoSocial) {
        this.empRazaoSocial = empRazaoSocial;
    }
    
    public String Usuarios.getEmail() {
        return email;
    }
    
    public void Usuarios.setEmail(String email) {
        this.email = email;
    }
    
    public String Usuarios.getRg() {
        return rg;
    }
    
    public void Usuarios.setRg(String rg) {
        this.rg = rg;
    }
    
    public String Usuarios.getTipoAcesso() {
        return tipoAcesso;
    }
    
    public void Usuarios.setTipoAcesso(String tipoAcesso) {
        this.tipoAcesso = tipoAcesso;
    }
    
    public String Usuarios.getTipoPessoa() {
        return tipoPessoa;
    }
    
    public void Usuarios.setTipoPessoa(String tipoPessoa) {
        this.tipoPessoa = tipoPessoa;
    }
    
    public String Usuarios.getTelefoneCelular() {
        return telefoneCelular;
    }
    
    public void Usuarios.setTelefoneCelular(String telefoneCelular) {
        this.telefoneCelular = telefoneCelular;
    }
    
    public String Usuarios.getFoto() {
        return foto;
    }
    
    public void Usuarios.setFoto(String foto) {
        this.foto = foto;
    }
    
}
